#page title
page_title                                : DesignPatternsApp                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6754806188                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : DesignPatterns                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Write a short tagline for your app.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Daniel Gogozan
your_link                                 : https://www.linkedin.com/in/daniel-gogozan-48a667209/
your_city                                 : Cluj-Napoca
email_address                             : gogozandaniel@gmail.com
linkedin_username                         : daniel-gogozan
linkedin_company                          :
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           : danielgogozan
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title: Flashcard-Based Learning
    description: Quickly learn each design pattern using concise, structured flashcards for efficient memorization
    fontawesome_icon_name: clone

  - title: Real-World Analogies
    description: Every pattern includes easy-to-understand real-world examples inspired by GoF to reinforce comprehension
    fontawesome_icon_name: lightbulb

  - title: UML Diagrams
    description: Visualize every pattern through clear, accurate UML class and sequence diagrams
    fontawesome_icon_name: project-diagram

  - title: Quizzes
    description: Test your knowledge with tailored quizzes to reinforce learning and track improvement
    fontawesome_icon_name: question-circle

  - title: Earn Badges
    description: Unlock achievement badges as you progress through the catalog of design patterns
    fontawesome_icon_name: award

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#EA603E"
cover_overlay_transparency                : 0.5

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#041027"

link_color                                : "#30F956"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#C7D2D2"

feature_icons_foreground_color            : "#30F956"
feature_icons_background_color            : "#061C45"

social_icons_foreground_color             : "#EA603E"
social_icons_background_color             : "#061C45"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
